myproject/myproject/myproject/urls.py
from django.contrib import admin
from django.conf.urls import url # changed from path to url
from controlcenter.views import controlcenter

from boards import views #added

urlpatterns = [
    url(r'^$', views.home, name='home'), # added; path or url?
    # url(r'^admin/', admin.site.urls),  # added
    url(r'^donors/(?P<pk>\d+)/$', views.donationsinfo, name='donationsinfo'),
    url(r'^donors/(?P<pk>\d+)/new/$', views.new_donations, name='new_donations'),
    url(r'^admin/', admin.site.urls),  # this is the original
    url(r'^donors/(?P<pk>\d+)/detail/$', views.detail_info, name='detail_info')
]

# so this one works, i don't know why

myproject/myproject/urls.py
from django.contrib import admin
from django.conf.urls import url # changed from path to url

from django.urls import include, path
#from controlcenter.views import controlcenter

from boards import views #added

urlpatterns = [
    url(r'^$', views.home, name='home'), # added; path or url?
    # url(r'^admin/', admin.site.urls),  # added
    url(r'^donors/(?P<pk>\d+)/$', views.donationsinfo, name='donationsinfo'),
    url(r'^donors/(?P<pk>\d+)/new/$', views.new_donations, name='new_donations'),
    url(r'^dashboard/(?P<pk>\d+)/$', views.dashboard, name='dashboard'),
    url(r'^admin/', admin.site.urls),  # this is the original

    #url(r'^admin/dashboard/', controlcenter.urls),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^donors/(?P<pk>\d+)/detail/$', views.detail_info, name='detail_info')

]

# so this one works, i don't know why

myproject/myproject/boards/models.py
from django.db import models

# Create your models here.

# below are copyed from the board project
from django.contrib.auth.models import User

from django.core.validators import MinLengthValidator

'''
class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='topics')

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='+')
'''

class Donor(models.Model):
    # this should be a one-to-many field (i think), have no idea if it's possible...
    donorname = models.CharField(max_length = 200)
    # invoicenum = models.CharField(max_length = 200)
    invoicenum = models.CharField(validators=[MinLengthValidator(10)], max_length = 10, blank = False, default = '2019')
    number_of_donations = models.IntegerField(default = 1)
    donor_email = models.CharField(max_length = 1000)
    # donor_phone = models.IntegerField(unique = True)
    donor_phone = models.CharField(max_length = 100)
    donor_address = models.CharField(max_length = 2000)
    last_updated = models.DateTimeField(auto_now_add = True)
    # item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name = 'donors')
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'donors')


class Item(models.Model):

    warehousenum = models.CharField(validators=[MinLengthValidator(10)], max_length = 10, blank = False)
    manufacturer = models.CharField(max_length = 300) # , choices = MANUFACTURER)
    item_model = models.CharField(max_length = 200)
    item_type = models.CharField(max_length = 200) # , choices = ITEM_TYPE)

    # recieved_date = models.DateTimeField(auto_now_add = True)

    # starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'items')

    starter = models.ForeignKey(User, on_delete=models.CASCADE, default=-1, related_name='items')
    invoice_nbr = models.ForeignKey(Donor, on_delete=models.CASCADE, default=-1, related_name='donor')




class Type(models.Model):
    # type_of_item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name = 'types')
    serialnum = models.CharField(validators=[MinLengthValidator(10)], max_length = 10, blank = False)
    cpu_type = models.CharField(max_length = 200)
    speed = models.CharField(max_length = 200)
    memory_mb = models.CharField(max_length = 200)
    hd_size = models.CharField(max_length = 200)
    screen_size = models.CharField(max_length = 200)
    cd_type = models.CharField(max_length = 200)
    operating_system = models.CharField(max_length = 200)
    power_test = models.CharField(max_length = 100, default='--')

    # starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='types')
    warehouse_nbr = models.ForeignKey(Item, on_delete=models.CASCADE, default=-1, related_name='item' )

class Test(models.Model):
    POWER_TEST = (
        ('Y', 'Pass.'),
        ('N', 'Fail.')
    )
    power_test = models.CharField(max_length = 100, choices = POWER_TEST, default='--')
    tested_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'tests')

class Evaluation(models.Model):
    # evaluation_stage = models.ForeignKey(Item, on_delete=models.CASCADE, related_name = 'evaluation')
    evaluated_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'evaluation')
    evaluated_at = models.DateTimeField(auto_now_add = True)

myproject/myproject/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}reBOOT Canada Database{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

myproject/myproject/templates/donationsinfo.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ donors.donorname }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">reBOOT Canada Database</a>
    </div>
  </nav>

  <body>
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Donors</a></li>
        <li class="breadcrumb-item active">{{ donors.donorname }}</li>
      </ol>

      <div class="mb-4">
        <a class="btn btn-primary" href="{% url 'new_donations' pk=invoice.id %}">New Donation</a>
      </div>

      <table class="table">
        <thead class="thead-inverse">
          <tr>

            <th>Warehouse Number</th>
            <th>Manufacturer</th>
            <th>Type</th>
            <th>Model</th>
            <th>Value</th>
            <th>Staff</th>

          </tr>
        </thead>
        <tbody>
          {% for item in items.all %}

            <tr>

              <td>
                <a href="{% url 'detail_info' pk=item.id %}">{{ item.warehousenum }}</a>
              </td>

              <td class = 'align-middle'>{{ item.manufacturer }}</td>
              <td class = 'align-middle'>{{ item.item_type }}</td>
              <td class = 'align-middle'>{{ item.item_model }}</td>
              <td>blah</td>
              <td class = 'align-middle'>{{ item.starter }}</td>

            </tr>

          {% endfor %}

        </tbody>
      </table>
    </div>
  </body>
</html>

myproject/myproject/templates/home.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>reBOOT Database</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">reBOOT Canada Database</a>
      </div>
    </nav>


    <div class="container">
        <ol class="breadcrumb my-4">
          <li class="breadcrumb-item active">Donations</li>
        </ol>
        <table class="table">
          <thead class="thead-inverse">
            <tr>
              <th>Donor</th>
              <th>Number of Donations</th>
              <th>Contact Information</th>
              <th>Address</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            {% for donor in donors %}
              <tr>
                <td>

                  <a href="{% url 'donationsinfo' donor.pk %}">{{ donor.donorname }}</a>
                  <small class = "text-muted d-block">{{ donor.invoicenum }}</small>

                </td>
                <td class = 'align-middle'>{{ donor.number_of_donations }}</td>
                <td>

                  <a class = 'align-middle'>{{ donor.donor_phone }}<a/>
                  <small class = "text-muted d-block">{{ donor.donor_email }}</small>

                </td>
                <td class = 'align-middle'>{{ donor.donor_address }}</td>
                <td class = 'align-middle'>{{ donor.last_updated }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </body>
  </html>

myproject/myproject/templates/new_donations.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Donations</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">reBOOT Canada Database</a>
    </div>
  </nav>


  <body>
    <div class="container">
      <ol class="breadcrumb my-4">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Donors</a></li>
          <li class="breadcrumb-item"><a href="{% url 'donationsinfo' donations.pk %}">{{ donations.donorname }}</a></li>
          <li class="breadcrumb-item active">New Donations</li>
      </ol>

      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_subject">Warehouse Number</label>
          <input type="text" class="form-control" id="id_warehousenum" name="warehousenum">
        </div>
        <div class="form-group">
          <label for="id_subject">Serial Number</label>
          <input type="text" class="form-control" id="id_serialnum" name="serialnum">
        </div>
        <div class="form-group">
          <label for="id_message">Manufacturer</label>
          <select type="text" class="form-control" id="id_manufacturer" name="manufacturer">
            <option value="apple">Apple</option>
            <option value="dell">Dell</option>
            <option value="Google">Google</option>
            <option value="hp">HP</option>
            <option value="lenovo">Lenovo</option>
            <option value="microsoft">MicroSoft</option>
            <option value="sony">Sony</option>
            <option value="other">Other</option>
          </select>
        </div>
        <div class="form-group">
          <label for="id_subject">Model</label>
          <input type="text" class="form-control" id="id_model" name="model">
        </div>
        <div class="form-group">
          <label for="id_message">Item Type</label>
          <select type="text" class="form-control" id="id_item_type" name="item_type">
            <option value="laptop">Laptop</option>
            <option value="desktop">Desktop</option>
            <option value="printer">Printer</option>
            <option value="harddrive">HardDrive</option>
            <option value="other">Other</option>
          </select>
        </div>
        <div class="form-group">
          <label for="id_subject">CPU Type</label>
          <input type="text" class="form-control" id="id_cpu_type" name="cpu_type">
        </div>
        <div class="form-group">
          <label for="id_subject">Speed</label>
          <input type="text" class="form-control" id="id_speed" name="speed">
        </div>
        <div class="form-group">
          <label for="id_subject">Memory (MB)</label>
          <input type="text" class="form-control" id="id_memory_mb" name="memory_mb">
        </div>
        <div class="form-group">
          <label for="id_subject">HD Size (GB)</label>
          <input type="text" class="form-control" id="id_hd_size" name="hd_size">
        </div>
        <div class="form-group">
          <label for="id_subject">Screen Size</label>
          <input type="text" class="form-control" id="id_screen_size" name="screen_size">
        </div>
        <div class="form-group">
          <label for="id_subject">CD Type</label>
          <input type="text" class="form-control" id="id_cd_type" name="cd_type">
        </div>
        <div class="form-group">
          <label for="id_subject">Operating System</label>
          <input type="text" class="form-control" id="id_operating_system" name="operating_system">
        </div>
        <div class="form-group">
          <label for="id_message">Power Test</label>
          <select type="text" class="form-control" id="id_power_test" name="power_test" >
            <option value="yes">Yes</option>
            <option value="no">No</option>
          </select>
        </div>
        

        <button type="submit" class="btn btn-success">Post</button>
      </form>
    </div>
  </body>
</html>